### ISSUE TITLE
Suggestion: Display configuration automatic or uEnv.txt based

### ISSUE THREAD

**Issue by ThomasKaiser** [ayufan-pine64/device-pine64-common#2]
Please have a look at https://github.com/igorpecovnik/lib/blob/master/config/bootscripts/boot-pine64.cmd#L35-L44

Boot script can react on settings present in `uEnvt.txt` or environment (autodetect touchpad controller?) and then modify settings on the fly (for example defining LCD as `display0` and setting HDMI resolution for `display1` appropriately)

**Comment by ayufan** [comment]
It will be configurable with uEnv.txt
