### ISSUE TITLE
vendorsetup:sdcard_image doesn't work properly

### ISSUE THREAD

**Issue by mikeygao** [ayufan-pine64/device-pine64-common#4]
sdcard_image pine64_android_7_1.img.gz
(device/pine64-common/vendorsetup.sh)

    cat <<EOF | sfdisk "$out"
$((part_position*mbs)),$((boot_size*mbs)),6
$(((part_position+boot_size)*mbs)),$((system_size/512)),L
$(((part_position+boot_size)*mbs)),$((cache_size/512)),L
$(((part_position+boot_size)*mbs)),$((data_size/512)),L
EOF

This line of code doesn't create valid partition table on image. Why system, cache, data start at the same position?

**Comment by ayufan** [comment]
It does. You can see that on my Jenkins using Ubuntu 16.04. It is possible that older version of sfdisk doesn't support this behavior, using the same start position makes the code to use next available partition.
